### ISSUE TITLE
Difference between hasUnit and hasUnitSymbol

### ISSUE THREAD

**Issue by paulzierep** [emmo-repo/datamodel-ontology#4]
Both relations range a xsd:string and have the example (m/s); which should be used when ? 
Also in EMMO are classes not literals and EMMO does also include the hasReferenceUnit object property. Do I correctly assume, that hasUnit and hasUnitSymbol are used here as a simplification, because it's difficult to map the correct unit class ?

**Comment by jesper-friis** [comment]
Thanks for the notification. This has been corrected in the current version.
