### ISSUE TITLE
Add inferred ontology

### ISSUE THREAD

**Issue by MBueschelberger** [emmo-repo/datamodel-ontology#5]
Hi @jesper-friis , 

I am currenlty including a specification for the installation of this ontology within osp-core. The result of my implementation will make it pico-installable via cmdline (e.g. `pico install datamodel` or `pico install datamodel.v0xyz` ). 

Would it be possible to add an inferred serialization of the datamodel ontology, hence I can add it as [rawgithub](https://github.com/simphony/osp-core/blob/519f1ffe86d006548b965c4feda2530547900bd0/osp/core/ontology/docs/datamodel.yml#L2) to the yml-specification.

Best wishes
Matthias

**Comment by jesper-friis** [comment]
We can make a github pages and placed it there. Do you need the inferred version of the whole datamodel (including EMMO) or just the metamodel (without EMMO)?

**Comment by jesper-friis** [comment]
I have now created a gh-pages branch with the inferred files:
- https://emmo-repo.github.io/datamodel-ontology/versions/0.0.2/entity-inferred.ttl
- https://emmo-repo.github.io/datamodel-ontology/versions/0.0.2/metamodel-inferred.ttl
- https://emmo-repo.github.io/datamodel-ontology/versions/0.0.2/datamodel-inferred.ttl


Todo:
- add a github action that updates these files for each release
- for push to master we should update https://emmo-repo.github.io/datamodel-ontology/latest/
- add an auto-generated index.html file that with links to these files
